# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model
from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship
from swagger_server.database.database import Base


class Account(Model, Base):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    __tablename__ = 'account'
    _account_id = Column(Integer, primary_key=True)
    _account_username = Column(String(255), nullable=True)
    _account_password = Column(String(65), nullable=True)
    _account_email = Column(String(255), unique=True, nullable=True)

    #_project_team_leader = relationship("Account", uselist=False, back_populates="account")
    #_project_secretary = relationship("Account", uselist=False, back_populates="parent")
    #_team_leader = relationship("Project", uselist=False, back_populates="account")
    #_secretary = relationship("Project", uselist=False, back_populates="account")

    def __init__(self, account_id: int=None, account_username: str=None, account_email: str=None, account_password: str=None):
        """
        Account - a model defined in Swagger

        :param account_id: The account_id of this Account.
        :type account_id: int
        :param account_username: The account_username of this Account.
        :type account_username: str
        :param account_email: The account_email of this Account.
        :type account_email: str
        :param account_password: The account_password of this Account.
        :type account_password: str
        """
        self.swagger_types = {
            'account_id': int,
            'account_username': str,
            'account_email': str,
            'account_password': str
        }

        self.attribute_map = {
            'account_id': 'account_id',
            'account_username': 'account_username',
            'account_email': 'account_email',
            'account_password': 'account_password'
        }

        self._account_id = account_id
        self._account_username = account_username
        self._account_email = account_email
        self._account_password = account_password

    @classmethod
    def from_dict(cls, dikt) -> 'Account':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Account of this Account.
        :rtype: Account
        """
        return deserialize_model(dikt, cls)

    @property
    def account_id(self) -> int:
        """
        Gets the account_id of this Account.
        Account identifier

        :return: The account_id of this Account.
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id: int):
        """
        Sets the account_id of this Account.
        Account identifier

        :param account_id: The account_id of this Account.
        :type account_id: int
        """

        self._account_id = account_id

    @property
    def account_username(self) -> str:
        """
        Gets the account_username of this Account.
        Account username

        :return: The account_username of this Account.
        :rtype: str
        """
        return self._account_username

    @account_username.setter
    def account_username(self, account_username: str):
        """
        Sets the account_username of this Account.
        Account username

        :param account_username: The account_username of this Account.
        :type account_username: str
        """

        self._account_username = account_username

    @property
    def account_email(self) -> str:
        """
        Gets the account_email of this Account.
        Account email

        :return: The account_email of this Account.
        :rtype: str
        """
        return self._account_email

    @account_email.setter
    def account_email(self, account_email: str):
        """
        Sets the account_email of this Account.
        Account email

        :param account_email: The account_email of this Account.
        :type account_email: str
        """

        self._account_email = account_email

    @property
    def account_password(self) -> str:
        """
        Gets the account_password of this Account.
        Account password

        :return: The account_password of this Account.
        :rtype: str
        """
        return self._account_password

    @account_password.setter
    def account_password(self, account_password: str):
        """
        Sets the account_password of this Account.
        Account password

        :param account_password: The account_password of this Account.
        :type account_password: str
        """

        self._account_password = account_password

