# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, account_id: int=None, token: str=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param account_id: The account_id of this InlineResponse200.
        :type account_id: int
        :param token: The token of this InlineResponse200.
        :type token: str
        """
        self.swagger_types = {
            'account_id': int,
            'token': str
        }

        self.attribute_map = {
            'account_id': 'accountId',
            'token': 'token'
        }

        self._account_id = account_id
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def account_id(self) -> int:
        """
        Gets the account_id of this InlineResponse200.

        :return: The account_id of this InlineResponse200.
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id: int):
        """
        Sets the account_id of this InlineResponse200.

        :param account_id: The account_id of this InlineResponse200.
        :type account_id: int
        """

        self._account_id = account_id

    @property
    def token(self) -> str:
        """
        Gets the token of this InlineResponse200.

        :return: The token of this InlineResponse200.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """
        Sets the token of this InlineResponse200.

        :param token: The token of this InlineResponse200.
        :type token: str
        """

        self._token = token

