# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Project(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, project_id: int=None, project_name: str=None):
        """
        Project - a model defined in Swagger

        :param project_id: The project_id of this Project.
        :type project_id: int
        :param project_name: The project_name of this Project.
        :type project_name: str
        """
        self.swagger_types = {
            'project_id': int,
            'project_name': str
        }

        self.attribute_map = {
            'project_id': 'project_id',
            'project_name': 'project_name'
        }

        self._project_id = project_id
        self._project_name = project_name

    @classmethod
    def from_dict(cls, dikt) -> 'Project':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project of this Project.
        :rtype: Project
        """
        return deserialize_model(dikt, cls)

    @property
    def project_id(self) -> int:
        """
        Gets the project_id of this Project.
        Project identifier

        :return: The project_id of this Project.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: int):
        """
        Sets the project_id of this Project.
        Project identifier

        :param project_id: The project_id of this Project.
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def project_name(self) -> str:
        """
        Gets the project_name of this Project.
        Project Name

        :return: The project_name of this Project.
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name: str):
        """
        Sets the project_name of this Project.
        Project Name

        :param project_name: The project_name of this Project.
        :type project_name: str
        """

        self._project_name = project_name

