# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SupportSystem(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, support_system_id: int=None, support_system_name: str=None):
        """
        SupportSystem - a model defined in Swagger

        :param support_system_id: The support_system_id of this SupportSystem.
        :type support_system_id: int
        :param support_system_name: The support_system_name of this SupportSystem.
        :type support_system_name: str
        """
        self.swagger_types = {
            'support_system_id': int,
            'support_system_name': str
        }

        self.attribute_map = {
            'support_system_id': 'support_system_id',
            'support_system_name': 'support_system_name'
        }

        self._support_system_id = support_system_id
        self._support_system_name = support_system_name

    @classmethod
    def from_dict(cls, dikt) -> 'SupportSystem':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SupportSystem of this SupportSystem.
        :rtype: SupportSystem
        """
        return deserialize_model(dikt, cls)

    @property
    def support_system_id(self) -> int:
        """
        Gets the support_system_id of this SupportSystem.
        Support system identifier

        :return: The support_system_id of this SupportSystem.
        :rtype: int
        """
        return self._support_system_id

    @support_system_id.setter
    def support_system_id(self, support_system_id: int):
        """
        Sets the support_system_id of this SupportSystem.
        Support system identifier

        :param support_system_id: The support_system_id of this SupportSystem.
        :type support_system_id: int
        """

        self._support_system_id = support_system_id

    @property
    def support_system_name(self) -> str:
        """
        Gets the support_system_name of this SupportSystem.
        Support system name

        :return: The support_system_name of this SupportSystem.
        :rtype: str
        """
        return self._support_system_name

    @support_system_name.setter
    def support_system_name(self, support_system_name: str):
        """
        Sets the support_system_name of this SupportSystem.
        Support system name

        :param support_system_name: The support_system_name of this SupportSystem.
        :type support_system_name: str
        """

        self._support_system_name = support_system_name

