# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.support_system_organization_unit import SupportSystemOrganizationUnit
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SupportSystemOrganizationUnitMatrix(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        SupportSystemOrganizationUnitMatrix - a model defined in Swagger

        """
        self.swagger_types = {
            
        }

        self.attribute_map = {
            
        }


    @classmethod
    def from_dict(cls, dikt) -> 'SupportSystemOrganizationUnitMatrix':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SupportSystemOrganizationUnitMatrix of this SupportSystemOrganizationUnitMatrix.
        :rtype: SupportSystemOrganizationUnitMatrix
        """
        return deserialize_model(dikt, cls)
